version: '3.9'

services:
  nginx:
    depends_on:
      - backand
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/stocks_products

  backend:
    depends_on:
      - db-postgres
      - migrations
    image: stocks_products
    build:
#      context: stocks_products
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
            gunicorn stocks_products.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/stocks_products
    networks:
      - backend

#  migrations:
#    image: stocks_products
##    build: .
#    command: python manage.py migrate --noinput
#    env_file:
#      - .env
#    container_name: migrations
#    depends_on:
#      - db-postgres

  db-postgres:
    image: postgres
    env_file:
      - .env
    container_name: db-postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg-data:
networks:
  backend:
